# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qube < Formula
  desc "qube is a DB load testing tool."
  homepage "https://github.com/winebarrel/qube"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qube/releases/download/v1.0.3/qube_1.0.3_darwin_amd64.tar.gz"
      sha256 "80e481b75c995170d6851aacb6046c795101086b4aeb9f0bb79e3c7b1ba210e5"

      def install
        bin.install 'qube'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/qube/releases/download/v1.0.3/qube_1.0.3_darwin_arm64.tar.gz"
      sha256 "26233f1eb92baf36af82a011b3487f42ce40e709b60446cbaa7637c98d348720"

      def install
        bin.install 'qube'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/qube/releases/download/v1.0.3/qube_1.0.3_linux_arm64.tar.gz"
      sha256 "64135dba2ec5630b5aa1475f3e3b0e0ce7d4ccb6f61ccff0dcd18900cee3ce44"

      def install
        bin.install 'qube'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qube/releases/download/v1.0.3/qube_1.0.3_linux_amd64.tar.gz"
      sha256 "4eaccfb56f8067386576f3ce7a6ae123fbe31f99cdc28877d847ee3447b69492"

      def install
        bin.install 'qube'
      end
    end
  end
end
