# This file was generated by GoReleaser. DO NOT EDIT.
cask "qube" do
  name "qube"
  desc "qube is a DB load testing tool."
  homepage "https://github.com/winebarrel/qube"
  version "1.7.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qube"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_darwin_amd64.tar.gz"
      sha256 "46741ce83ca0da5c8ef6d4a5b1c57b0235180a433986f0bd7efb50ad54c6a4d3"
    end
    on_arm do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_darwin_arm64.tar.gz"
      sha256 "cbe14220fac7dffb2b65dd15dc11973b73e689b5d46abfc4cbbe60756b14a7a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_linux_amd64.tar.gz"
      sha256 "0e302e2c30ab4c43db2bc6525f588e7585fc29061ce88358b8840cd6878257f1"
    end
    on_arm do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_linux_arm64.tar.gz"
      sha256 "747fdba95e762a26eec47fae2cd60b1ce19e64e8fc06febd9388db2189b4d60a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qube"]
    end
  end

  # No zap stanza required
end
