# This file was generated by GoReleaser. DO NOT EDIT.
cask "qube" do
  name "qube"
  desc "qube is a DB load testing tool."
  homepage "https://github.com/winebarrel/qube"
  version "1.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qube"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_darwin_amd64.tar.gz"
      sha256 "da286c9581a23c6961e2b7a4c630214eff8bbe220b3acb269c7ed22b488d6ce1"
    end
    on_arm do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_darwin_arm64.tar.gz"
      sha256 "a45f22057412c06753b1b56a8b086cbfb5f4d95b8d9f13cdbbc339cdc83ccdce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_linux_amd64.tar.gz"
      sha256 "db8e7d50e8ed646ad635965ac3c56edb1aec456c1e7b5b9e55fc92670b9309a9"
    end
    on_arm do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_linux_arm64.tar.gz"
      sha256 "a8cf9144f6767c4c9e821fbf6b11e219cfd424cdec01e53277781be16717917c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qube"]
    end
  end

  # No zap stanza required
end
