# This file was generated by GoReleaser. DO NOT EDIT.
cask "qube" do
  name "qube"
  desc "qube is a DB load testing tool."
  homepage "https://github.com/winebarrel/qube"
  version "1.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qube"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_darwin_amd64.tar.gz"
      sha256 "9a436c81572d484bcf89c2e5099a0d5cf00966b2e3f839881fadca4e7876f61c"
    end
    on_arm do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_darwin_arm64.tar.gz"
      sha256 "6e0e6a3acd1d394c1df78255da53f5b8047f62897b85a11094db7448d97c1c48"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_linux_amd64.tar.gz"
      sha256 "0287005af296b51e6dc4210dfd14ebb95c2831b6cd85b952bbcde7502952df80"
    end
    on_arm do
      url "https://github.com/winebarrel/qube/releases/download/v#{version}/qube_#{version}_linux_arm64.tar.gz"
      sha256 "3fe2495a3b3592a280b7eea4b42bf97554c44665b45e4746a2ef7b70df0664b6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qube"]
    end
  end

  # No zap stanza required
end
